language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
  - "pypy"
install:
  - pip install six coveralls
script:
  coverage run --source=mls setup.py test
after_success:
  coveralls
